FROM node:22.19.0-alpine3.22

RUN apk update
RUN apk upgrade
RUN apk add --no-cache ffmpeg

WORKDIR /app

COPY ./packages ./packages

COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json

COPY ./apps/transcoder ./apps/transcoder

RUN npm i -g pnpm
RUN pnpm install
RUN pnpm run transcoder:build

CMD ["pnpm", "run", "transcoder:start"]
