FROM node:22.19.0-alpine3.22

WORKDIR /app

COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json

RUN npm i -g pnpm
RUN pnpm i --frozen-lockfile

COPY ./packages ./packages
COPY ./apps/web ./apps/web

RUN pnpm db:generate
RUN pnpm web:build

EXPOSE 3000

CMD [ "pnpm", "run", "web:start" ]