FROM node:22.19.0-alpine3.22

WORKDIR /app

COPY ./packages ./packages

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json

COPY ./apps/consumer ./apps/consumer

RUN npm i -g pnpm
RUN pnpm i
RUN pnpm run consumer:build

CMD [ "pnpm run consumer:start" ]